import { PERMISSIONS } from '../../security/permissions.js';

import type { AuthorizationPolicy } from '../../middlewares/authorization.js';

export const adminAuthorizationPolicies = [
    { method: 'get', path: '/audit-logs', permission: PERMISSIONS.auditRead },
    { method: 'get', path: '/catalog-proposals', permission: PERMISSIONS.catalogManage },
    { method: 'post', path: '/catalog-proposals/tags/:id/accept', permission: PERMISSIONS.catalogManage },
    { method: 'post', path: '/catalog-proposals/ingredients/:id/accept', permission: PERMISSIONS.catalogManage },
    { method: 'post', path: '/catalog-proposals/:id/reject', permission: PERMISSIONS.catalogManage },
    { method: 'post', path: '/catalog-proposals/tags/:id/associate', permission: PERMISSIONS.catalogManage },
    { method: 'post', path: '/catalog-proposals/ingredients/:id/associate', permission: PERMISSIONS.catalogManage },
    { method: 'post', path: '/catalog-proposals/ingredients/:id/alias', permission: PERMISSIONS.catalogManage },
    { method: 'get', path: '/comments/moderated', permission: PERMISSIONS.commentReview },
    { method: 'get', path: '/comments/moderated/count', permission: PERMISSIONS.commentReview },
    { method: 'get', path: '/comments/soft-deleted', permission: PERMISSIONS.commentReview },
    { method: 'get', path: '/comments/soft-deleted/count', permission: PERMISSIONS.commentReview },
    { method: 'post', path: '/comments/:id/hide', permission: PERMISSIONS.commentHide },
    { method: 'post', path: '/comments/:id/unmoderate', permission: PERMISSIONS.commentRestore },
    { method: 'post', path: '/comments/:id/restore', permission: PERMISSIONS.commentRestore },
    { method: 'patch', path: '/comments/:id', permission: PERMISSIONS.commentsUpdate },
    { method: 'delete', path: '/comments/:id', permission: PERMISSIONS.commentsDelete },
    { method: 'get', path: '/recipes/pending', permission: PERMISSIONS.recipeReview },
    { method: 'get', path: '/recipes/pending/count', permission: PERMISSIONS.recipeReview },
    { method: 'get', path: '/recipes/:id', permission: PERMISSIONS.recipeReview },
    { method: 'post', path: '/recipes/:id/approve', permission: PERMISSIONS.recipePublish },
    { method: 'post', path: '/recipes/:id/reject', permission: PERMISSIONS.recipeReject },
    { method: 'post', path: '/recipes/:id/archive', permission: PERMISSIONS.recipeArchive },
    { method: 'delete', path: '/recipes/:id', permission: PERMISSIONS.recipesDelete },
    { method: 'get', path: '/users/banned', permission: PERMISSIONS.userRead },
    { method: 'get', path: '/users/banned/count', permission: PERMISSIONS.userRead },
    { method: 'get', path: '/users/:id', permission: PERMISSIONS.userRead },
    { method: 'post', path: '/users/:id/ban', permission: PERMISSIONS.userBan },
    { method: 'post', path: '/users/:id/unban', permission: PERMISSIONS.userUnban },
    { method: 'post', path: '/staff/invitations', permission: PERMISSIONS.staffCreate },
    { method: 'get', path: '/staff', permission: PERMISSIONS.staffRead },
    { method: 'get', path: '/staff/:staffUserId', permission: PERMISSIONS.staffRead },
    { method: 'post', path: '/staff/:staffUserId/disable', permission: PERMISSIONS.staffDisable },
    { method: 'post', path: '/staff/:staffUserId/enable', permission: PERMISSIONS.staffEnable },
    { method: 'post', path: '/staff/:staffUserId/roles/:roleCode', permission: PERMISSIONS.staffRoleGrant },
    { method: 'delete', path: '/staff/:staffUserId/roles/:roleCode', permission: PERMISSIONS.staffRoleRevoke },
    { method: 'get', path: '/staff/:staffUserId/sessions', permission: PERMISSIONS.staffRead },
    { method: 'delete', path: '/staff/:staffUserId/sessions/:sessionId', permission: PERMISSIONS.staffSessionRevoke },
    { method: 'get', path: '/tags', permission: PERMISSIONS.tagRead },
    { method: 'post', path: '/tags', permission: PERMISSIONS.tagCreate },
    { method: 'patch', path: '/tags/:id', permission: PERMISSIONS.tagUpdate },
    { method: 'post', path: '/tags/:id/deprecate', permission: PERMISSIONS.tagDeprecate },
    { method: 'post', path: '/tags/:id/restore', permission: PERMISSIONS.tagDeprecate },
    { method: 'post', path: '/tags/:id/merge', permission: PERMISSIONS.tagMerge },
    { method: 'get', path: '/ingredients', permission: PERMISSIONS.ingredientRead },
    { method: 'post', path: '/ingredients', permission: PERMISSIONS.ingredientCreate },
    { method: 'patch', path: '/ingredients/:id', permission: PERMISSIONS.ingredientUpdate },
    { method: 'post', path: '/ingredients/:id/deprecate', permission: PERMISSIONS.ingredientDeprecate },
    { method: 'post', path: '/ingredients/:id/restore', permission: PERMISSIONS.ingredientDeprecate },
    { method: 'post', path: '/ingredients/:id/merge', permission: PERMISSIONS.ingredientMerge },
    { method: 'get', path: '/ingredients/:id/aliases', permission: PERMISSIONS.ingredientRead },
    { method: 'post', path: '/ingredients/:id/aliases', permission: PERMISSIONS.ingredientAliasManage },
    { method: 'patch', path: '/ingredients/:id/aliases/:aliasId', permission: PERMISSIONS.ingredientAliasManage },
    { method: 'delete', path: '/ingredients/:id/aliases/:aliasId', permission: PERMISSIONS.ingredientAliasManage }
] as const satisfies readonly AuthorizationPolicy[];
