USE recipe_shelter;

SET NAMES utf8mb4;

START TRANSACTION;

-- =====================================================
-- Roles
-- =====================================================
INSERT INTO Roles (Id, Name) VALUES
(1, 'admin'),
(2, 'user'),
(3, 'anonyme')
AS new_roles
ON DUPLICATE KEY UPDATE Name = new_roles.Name;

-- =====================================================
-- Users
-- =====================================================

-- Admin
INSERT INTO Users (Id, Mail, Username, Password, RoleId, Status, EmailValidatedAt)
VALUES (
  1,
  'admin@recipe-shelter.fr',
  'Admin',
  '$2b$12$zrX5iMCRel.f0GtuWfc2J.w8rq7bSuNnFnpd6.ODVPEGhgZlygfBW',
  1,
  'active',
  CURRENT_TIMESTAMP
) AS new_admin
ON DUPLICATE KEY UPDATE
  Username  = new_admin.Username,
  Password  = new_admin.Password,
  RoleId    = new_admin.RoleId,
  Status    = new_admin.Status,
  EmailValidatedAt = COALESCE(EmailValidatedAt, new_admin.EmailValidatedAt);

-- Anonyme
INSERT INTO Users (Id, Mail, Username, Password, RoleId, Status, EmailValidatedAt)
VALUES (
  2,
  'anonyme@recipe-shelter.fr',
  'Anonyme',
  '$2b$12$REPLACE_WITH_REAL_HASH_FOR_ANONYME_USER',
  3,
  'active',
  CURRENT_TIMESTAMP
) AS new_anonyme
ON DUPLICATE KEY UPDATE
  Username  = new_anonyme.Username,
  RoleId    = new_anonyme.RoleId,
  Status    = new_anonyme.Status,
  EmailValidatedAt = COALESCE(EmailValidatedAt, new_anonyme.EmailValidatedAt);

-- =====================================================
-- Recipe Categories
-- =====================================================
INSERT INTO RecipeCategories (Name, Slug, IconName) VALUES
('Apéritif',        'aperitif',        'snack'),
('Boissons',        'boissons',        'glass'),
('Dessert',         'dessert',         'cake'),
('Entrée',          'entree',          'salad'),
('Petit-déjeuner',  'petit-dejeuner',  'croissant'),
('Plat principal',  'plat-principal',  'dish')
AS new_cats
ON DUPLICATE KEY UPDATE
  Name     = new_cats.Name,
  IconName = new_cats.IconName;

-- =====================================================
-- Ingredients (276)
-- =====================================================
INSERT INTO Ingredients (Name, Slug) VALUES
('Abondance', 'abondance'),
('Abricot', 'abricot'),
('Agar-agar', 'agar-agar'),
('Agneau', 'agneau'),
('Ail', 'ail'),
('Ail des ours', 'ail-des-ours'),
('Airelle', 'airelle'),
('Algue', 'algue'),
('Aloe vera', 'aloe-vera'),
('Amande', 'amande'),
('Amarante', 'amarante'),
('Ananas', 'ananas'),
('Anchois', 'anchois'),
('Andouillette', 'andouillette'),
('Aneth', 'aneth'),
('Anguille', 'anguille'),
('Angélique', 'angelique'),
('Anis', 'anis'),
('Araignée de mer', 'araignee-de-mer'),
('Arnica', 'arnica'),
('Artichaut', 'artichaut'),
('Asperge', 'asperge'),
('Aubergine', 'aubergine'),
('Aubépine', 'aubepine'),
('Avocat', 'avocat'),
('Babeurre', 'babeurre'),
('Bacon', 'bacon'),
('Badiane', 'badiane'),
('Baie rose', 'baie-rose'),
('Banane', 'banane'),
('Bar', 'bar'),
('Basilic', 'basilic'),
('Baudroie', 'baudroie'),
('Bavette', 'bavette'),
('Betterave', 'betterave'),
('Beurre', 'beurre'),
('Beurre demi-sel', 'beurre-demi-sel'),
('Beurre doux', 'beurre-doux'),
('Bicarbonate de soude', 'bicarbonate-de-soude'),
('Biscotte', 'biscotte'),
('Bière', 'biere'),
('Blanc de poulet', 'blanc-de-poulet'),
('Blette', 'blette'),
('Bleu d''Auvergne', 'bleu-d-auvergne'),
('Blé', 'ble'),
('Boeuf', 'boeuf'),
('Boeuf haché', 'boeuf-hache'),
('Bolet', 'bolet'),
('Bouillon de légumes', 'bouillon-de-legumes'),
('Bouillon de poulet', 'bouillon-de-poulet'),
('Boulgour', 'boulgour'),
('Bourrache', 'bourrache'),
('Brocoli', 'brocoli'),
('Brousse', 'brousse'),
('Brugnon', 'brugnon'),
('Cacahuète', 'cacahuete'),
('Cacao', 'cacao'),
('Café', 'cafe'),
('Caille', 'caille'),
('Calamar', 'calamar'),
('Camembert', 'camembert'),
('Canard', 'canard'),
('Cannelle', 'cannelle'),
('Cantal', 'cantal'),
('Capre', 'capre'),
('Caramel', 'caramel'),
('Cardamome', 'cardamome'),
('Carotte', 'carotte'),
('Cassis', 'cassis'),
('Cerfeuil', 'cerfeuil'),
('Cerise', 'cerise'),
('Champignon', 'champignon'),
('Cheddar', 'cheddar'),
('Chicorée', 'chicoree'),
('Chili', 'chili'),
('Chocolat', 'chocolat'),
('Chocolat au lait', 'chocolat-au-lait'),
('Chocolat blanc', 'chocolat-blanc'),
('Chocolat noir', 'chocolat-noir'),
('Chorizo', 'chorizo'),
('Chou', 'chou'),
('Chou blanc', 'chou-blanc'),
('Chou kale', 'chou-kale'),
('Chou-fleur', 'chou-fleur'),
('Châtaigne', 'chataigne'),
('Chèvre', 'chevre'),
('Ciboulette', 'ciboulette'),
('Cidre', 'cidre'),
('Citron', 'citron'),
('Citron vert', 'citron-vert'),
('Clou de girofle', 'clou-de-girofle'),
('Clémentine', 'clementine'),
('Coing', 'coing'),
('Comté', 'comte'),
('Concentré de tomate', 'concentre-de-tomate'),
('Concombre', 'concombre'),
('Coriandre', 'coriandre'),
('Cornichon', 'cornichon'),
('Courge', 'courge'),
('Courgette', 'courgette'),
('Couscous', 'couscous'),
('Crabe', 'crabe'),
('Cresson', 'cresson'),
('Crevette', 'crevette'),
('Crème fraîche', 'creme-fraiche'),
('Crème liquide', 'creme-liquide'),
('Crème épaisse', 'creme-epaisse'),
('Cumin', 'cumin'),
('Curcuma', 'curcuma'),
('Curry', 'curry'),
('Câpre', 'capre'),
('Céleri', 'celeri'),
('Céleri-rave', 'celeri-rave'),
('Datte', 'datte'),
('Dinde', 'dinde'),
('Edam', 'edam'),
('Emmental', 'emmental'),
('Endive', 'endive'),
('Estragon', 'estragon'),
('Farine', 'farine'),
('Fenouil', 'fenouil'),
('Feta', 'feta'),
('Figue', 'figue'),
('Foie gras', 'foie-gras'),
('Fond de veau', 'fond-de-veau'),
('Fraise', 'fraise'),
('Framboise', 'framboise'),
('Fromage blanc', 'fromage-blanc'),
('Fromage de chèvre', 'fromage-de-chevre'),
('Fusilli', 'fusilli'),
('Fève', 'feve'),
('Fécule de maïs', 'fecule-de-mais'),
('Gambas', 'gambas'),
('Gingembre', 'gingembre'),
('Gorgonzola', 'gorgonzola'),
('Gouda', 'gouda'),
('Graines de courge', 'graines-de-courge'),
('Grenade', 'grenade'),
('Gruyère', 'gruyere'),
('Haricot blanc', 'haricot-blanc'),
('Haricot rouge', 'haricot-rouge'),
('Haricot vert', 'haricot-vert'),
('Harissa', 'harissa'),
('Herbes de Provence', 'herbes-de-provence'),
('Huile d''olive', 'huile-d-olive'),
('Huile de sésame', 'huile-de-sesame'),
('Huile de tournesol', 'huile-de-tournesol'),
('Huître', 'huitre'),
('Jambon', 'jambon'),
('Ketchup', 'ketchup'),
('Kiwi', 'kiwi'),
('Lait', 'lait'),
('Lait d''amande', 'lait-d-amande'),
('Lait d''avoine', 'lait-d-avoine'),
('Lait de coco', 'lait-de-coco'),
('Laitue', 'laitue'),
('Langouste', 'langouste'),
('Lardons', 'lardons'),
('Laurier', 'laurier'),
('Lentille', 'lentille'),
('Lentille corail', 'lentille-corail'),
('Levure boulangère', 'levure-boulangere'),
('Levure chimique', 'levure-chimique'),
('Lieu noir', 'lieu-noir'),
('Litchi', 'litchi'),
('Mangue', 'mangue'),
('Mascarpone', 'mascarpone'),
('Mayonnaise', 'mayonnaise'),
('Maïs', 'mais'),
('Maïzena', 'maizena'),
('Melon', 'melon'),
('Menthe', 'menthe'),
('Miel', 'miel'),
('Mimolette', 'mimolette'),
('Moules', 'moules'),
('Moutarde', 'moutarde'),
('Moutarde à l''ancienne', 'moutarde-a-l-ancienne'),
('Mozzarella', 'mozzarella'),
('Muscade', 'muscade'),
('Myrtilles', 'myrtilles'),
('Mâche', 'mache'),
('Mûre', 'mure'),
('Navet', 'navet'),
('Nectarine', 'nectarine'),
('Noisette', 'noisette'),
('Noix', 'noix'),
('Noix de coco', 'noix-de-coco'),
('Noix de muscade', 'noix-de-muscade'),
('Noix de pécan', 'noix-de-pecan'),
('Noix de Saint-Jacques', 'noix-de-saint-jacques'),
('Nouille', 'nouille'),
('Oeuf', 'oeuf'),
('Oignon', 'oignon'),
('Oignon rouge', 'oignon-rouge'),
('Olive', 'olive'),
('Orange', 'orange'),
('Origan', 'origan'),
('Pamplemousse', 'pamplemousse'),
('Papaye', 'papaye'),
('Paprika', 'paprika'),
('Parmesan', 'parmesan'),
('Pastèque', 'pasteque'),
('Patate douce', 'patate-douce'),
('Persil', 'persil'),
('Pesto', 'pesto'),
('Petit pois', 'petit-pois'),
('Pignons de pin', 'pignons-de-pin'),
('Piment', 'piment'),
('Pistache', 'pistache'),
('Poire', 'poire'),
('Poireau', 'poireau'),
('Poivre blanc', 'poivre-blanc'),
('Poivre noir', 'poivre-noir'),
('Poivre vert', 'poivre-vert'),
('Poivron', 'poivron'),
('Polenta', 'polenta'),
('Pomme', 'pomme'),
('Pomme de terre', 'pomme-de-terre'),
('Porc', 'porc'),
('Poulet', 'poulet'),
('Prune', 'prune'),
('Pâtes', 'pates'),
('Pêche', 'peche'),
('Quinoa', 'quinoa'),
('Radis', 'radis'),
('Raifort', 'raifort'),
('Raquette', 'raquette'),
('Reblochon', 'reblochon'),
('Rhubarbe', 'rhubarbe'),
('Rhum', 'rhum'),
('Ricotta', 'ricotta'),
('Riz', 'riz'),
('Riz basmati', 'riz-basmati'),
('Romarin', 'romarin'),
('Roquefort', 'roquefort'),
('Roquette', 'roquette'),
('Safran', 'safran'),
('Saint-Nectaire', 'saint-nectaire'),
('Salade', 'salade'),
('Sauce béchamel', 'sauce-bechamel'),
('Sauce soja', 'sauce-soja'),
('Sauce tomate', 'sauce-tomate'),
('Sauce Worcestershire', 'sauce-worcestershire'),
('Saucisses', 'saucisses'),
('Sauge', 'sauge'),
('Saumon', 'saumon'),
('Sel', 'sel'),
('Semoule', 'semoule'),
('Sirop d''agave', 'sirop-d-agave'),
('Sirop de grenadine', 'sirop-de-grenadine'),
('Soja', 'soja'),
('Sole', 'sole'),
('Sucre', 'sucre'),
('Sucre glace', 'sucre-glace'),
('Sucre roux', 'sucre-roux'),
('Sésame', 'sesame'),
('Tapioca', 'tapioca'),
('Thon', 'thon'),
('Thym', 'thym'),
('Tofu', 'tofu'),
('Tomate', 'tomate'),
('Tomate cerise', 'tomate-cerise'),
('Truite', 'truite'),
('Vanille', 'vanille'),
('Veau', 'veau'),
('Vermicelle', 'vermicelle'),
('Vinaigre', 'vinaigre'),
('Vinaigre balsamique', 'vinaigre-balsamique'),
('Vinaigre de cidre', 'vinaigre-de-cidre'),
('Vinaigre de vin', 'vinaigre-de-vin'),
('Vodka', 'vodka'),
('Yaourt', 'yaourt'),
('Yaourt nature', 'yaourt-nature'),
('Échalote', 'echalote'),
('Écrevisse', 'ecrevisse'),
('Épinard', 'epinard')
AS new_row ON DUPLICATE KEY UPDATE Slug = new_row.Slug;

-- =====================================================
-- Tags (87)
-- =====================================================
INSERT INTO Tags (Name, Slug) VALUES
-- Régimes alimentaires
('Végétarien', 'vegetarien'),
('Vegan', 'vegan'),
('Sans gluten', 'sans-gluten'),
('Sans lactose', 'sans-lactose'),
('Sans sucre ajouté', 'sans-sucre-ajoute'),
('Cétogène', 'cetogene'),
('Halal', 'halal'),
('Casher', 'casher'),
('Sans noix', 'sans-noix'),
('Sans oeuf', 'sans-oeuf'),
('Sans porc', 'sans-porc'),
('Paléo', 'paleo'),
('Cru', 'cru'),
-- Nutrition
('Healthy', 'healthy'),
('Light', 'light'),
('Protéiné', 'proteine'),
('Riche en fibres', 'riche-fibres'),
('Faible en calories', 'faible-calories'),
('Riche en fer', 'riche-fer'),
('Riche en oméga-3', 'riche-omega-3'),
('Anti-inflammatoire', 'anti-inflammatoire'),
-- Difficulté
('Facile', 'facile'),
('Intermédiaire', 'intermediaire'),
('Difficile', 'difficile'),
-- Temps
('Très rapide', 'tres-rapide'),
('Rapide', 'rapide'),
('Longue cuisson', 'longue-cuisson'),
('Marinade', 'marinade'),
('Sans cuisson', 'sans-cuisson'),
('Une seule casserole', 'une-seule-casserole'),
-- Type de plat
('Entrée', 'entree'),
('Plat principal', 'plat-principal'),
('Dessert', 'dessert'),
('Accompagnement', 'accompagnement'),
('Sauce', 'sauce'),
('Soupe', 'soupe'),
('Salade', 'salade'),
('Snack', 'snack'),
('Apéritif', 'aperitif'),
('Petit-déjeuner', 'petit-dejeuner'),
('Boisson', 'boisson'),
('Pain & Viennoiserie', 'pain-viennoiserie'),
('Confiture & Conserve', 'confiture-conserve'),
-- Occasion
('Anniversaire', 'anniversaire'),
('Noël', 'noel'),
('Pâques', 'paques'),
('Saint-Valentin', 'saint-valentin'),
('Repas de fête', 'repas-fete'),
('Brunch', 'brunch'),
('Barbecue', 'barbecue'),
('Pique-nique', 'pique-nique'),
('Repas enfants', 'repas-enfants'),
('Ramadan', 'ramadan'),
('Halloween', 'halloween'),
('Nouvel An', 'nouvel-an'),
-- Ambiance / Style
('Comfort food', 'comfort-food'),
('Fait maison', 'fait-maison'),
('Économique', 'economique'),
('Batch cooking', 'batch-cooking'),
('Cuisine de saison', 'cuisine-saison'),
('Recette de grand-mère', 'recette-grand-mere'),
-- Technique
('Mijoté', 'mijote'),
('Grillé', 'grille'),
('Frit', 'frit'),
('Vapeur', 'vapeur'),
('Cuit au four', 'cuit-au-four'),
('Fermenté', 'fermente'),
('Fumé', 'fume'),
-- Cuisines du monde
('Cuisine française', 'cuisine-francaise'),
('Cuisine italienne', 'cuisine-italienne'),
('Cuisine asiatique', 'cuisine-asiatique'),
('Cuisine japonaise', 'cuisine-japonaise'),
('Cuisine chinoise', 'cuisine-chinoise'),
('Cuisine thaïlandaise', 'cuisine-thailandaise'),
('Cuisine indienne', 'cuisine-indienne'),
('Cuisine libanaise', 'cuisine-libanaise'),
('Cuisine mexicaine', 'cuisine-mexicaine'),
('Cuisine orientale', 'cuisine-orientale'),
('Cuisine méditerranéenne', 'cuisine-mediterraneenne'),
('Cuisine grecque', 'cuisine-grecque'),
('Cuisine espagnole', 'cuisine-espagnole'),
('Cuisine américaine', 'cuisine-americaine'),
('Cuisine africaine', 'cuisine-africaine'),
('Cuisine antillaise', 'cuisine-antillaise'),
('Cuisine brésilienne', 'cuisine-bresilienne')
AS new_row ON DUPLICATE KEY UPDATE Slug = new_row.Slug;

-- =====================================================
-- Equipments (83)
-- =====================================================
INSERT INTO Equipments (Name, Slug) VALUES
('Aiguille à brider', 'aiguille-a-brider'),
('Attendrisseur à viande', 'attendrisseur-a-viande'),
('Autocuiseur', 'autocuiseur'),
('Balance de cuisine', 'balance-de-cuisine'),
('Batteur électrique', 'batteur-electrique'),
('Bocal', 'bocal'),
('Bol mélangeur', 'bol-melangeur'),
('Bouilloire', 'bouilloire'),
('Brosse à pâtisserie', 'brosse-a-patisserie'),
('Broche', 'broche'),
('Casserole', 'casserole'),
('Casserole à lait', 'casserole-a-lait'),
('Cercle à pâtisserie', 'cercle-a-patisserie'),
('Chalumeau de cuisine', 'chalumeau-de-cuisine'),
('Chinois', 'chinois'),
('Ciseaux de cuisine', 'ciseaux-de-cuisine'),
('Corne de pâtisserie', 'corne-de-patisserie'),
('Couperet', 'couperet'),
('Coupe-œuf', 'coupe-uf'),
('Couteau à pain', 'couteau-a-pain'),
('Couteau d''office', 'couteau-d-office'),
('Couteau de cuisine', 'couteau-de-cuisine'),
('Couteau éminceur', 'couteau-eminceur'),
('Crêpière', 'crepiere'),
('Cuiseur vapeur', 'cuiseur-vapeur'),
('Cuillère en bois', 'cuillere-en-bois'),
('Cul-de-poule', 'cul-de-poule'),
('Découpoir', 'decoupoir'),
('Essoreuse à salade', 'essoreuse-a-salade'),
('Faitout', 'faitout'),
('Film alimentaire', 'film-alimentaire'),
('Fouet', 'fouet'),
('Four', 'four'),
('Fourchette de cuisine', 'fourchette-de-cuisine'),
('Friteuse', 'friteuse'),
('Gant de cuisine', 'gant-de-cuisine'),
('Gaufrier', 'gaufrier'),
('Grille-pain', 'grille-pain'),
('Grille de refroidissement', 'grille-de-refroidissement'),
('Hachoir', 'hachoir'),
('Lèchefrite', 'lechefrite'),
('Louche', 'louche'),
('Mandoline', 'mandoline'),
('Marmite', 'marmite'),
('Maryse', 'maryse'),
('Mixeur', 'mixeur'),
('Moule à cake', 'moule-a-cake'),
('Moule à manqué', 'moule-a-manque'),
('Moule à muffins', 'moule-a-muffins'),
('Moule à soufflé', 'moule-a-souffle'),
('Moule à tarte', 'moule-a-tarte'),
('Moule en silicone', 'moule-en-silicone'),
('Papier aluminium', 'papier-aluminium'),
('Papier cuisson', 'papier-cuisson'),
('Passoire', 'passoire'),
('Pelle à tarte', 'pelle-a-tarte'),
('Pilon', 'pilon'),
('Pince de cuisine', 'pince-de-cuisine'),
('Pinceau de cuisine', 'pinceau-de-cuisine'),
('Planche à découper', 'planche-a-decouper'),
('Plaque de cuisson', 'plaque-de-cuisson'),
('Plateau tournant', 'plateau-tournant'),
('Poche à douille', 'poche-a-douille'),
('Poêle', 'poele'),
('Poêle à crêpes', 'poele-a-crepes'),
('Presse-agrumes', 'presse-agrumes'),
('Presse-purée', 'presse-puree'),
('Ramequin', 'ramequin'),
('Robot de cuisine', 'robot-de-cuisine'),
('Rouleau à pâtisserie', 'rouleau-a-patisserie'),
('Râpe', 'rape'),
('Sac de congélation', 'sac-de-congelation'),
('Saladier', 'saladier'),
('Sauteuse', 'sauteuse'),
('Siphon de cuisine', 'siphon-de-cuisine'),
('Spatule', 'spatule'),
('Tamis', 'tamis'),
('Terrine', 'terrine'),
('Verre doseur', 'verre-doseur'),
('Wok', 'wok'),
('Zesteur', 'zesteur'),
('Écumoire', 'ecumoire'),
('Épluche-légumes', 'epluche-legumes')
AS new_row ON DUPLICATE KEY UPDATE Slug = new_row.Slug;

COMMIT;
