# ============================================
# Health
# ============================================

@baseUrl = http://localhost:3000/api/v1
@adminSessionCookie = PASTE_RS_ADMIN_SESSION_COOKIE_HERE

### Health live
GET {{baseUrl}}/health/live
Cookie: rs_admin_session={{adminSessionCookie}}

### Health ready
GET {{baseUrl}}/health/ready
Cookie: rs_admin_session={{adminSessionCookie}}

### Health
GET {{baseUrl}}/health
Cookie: rs_admin_session={{adminSessionCookie}}
