# ============================================
# Health
# ============================================

@baseUrl = http://localhost:3000/api/v1
@adminJwt = PASTE_ADMIN_JWT_HERE

### Health live
GET {{baseUrl}}/health/live
Authorization: Bearer {{adminJwt}}

### Health ready
GET {{baseUrl}}/health/ready
Authorization: Bearer {{adminJwt}}

### Health
GET {{baseUrl}}/health
Authorization: Bearer {{adminJwt}}
