# ============================================
# Users
# ============================================

@baseUrl = http://localhost:3000/api/v1
@sessionCookie = PASTE_RS_APP_SESSION_COOKIE_HERE
@password = Password123!
@newPassword = NewPassword123!

### User profile
GET {{baseUrl}}/users/me
Cookie: rs_app_session={{sessionCookie}}

### Update email
PATCH {{baseUrl}}/users/me/email
Content-Type: application/json
Cookie: rs_app_session={{sessionCookie}}

{
  "newEmail": "new-test@example.com",
  "currentPassword": "{{password}}"
}

### Update username
PATCH {{baseUrl}}/users/me/username
Content-Type: application/json
Cookie: rs_app_session={{sessionCookie}}

{
  "newUsername": "newtestuser",
  "currentPassword": "{{password}}"
}

### Update password
PATCH {{baseUrl}}/users/me/password
Content-Type: application/json
Cookie: rs_app_session={{sessionCookie}}

{
  "currentPassword": "{{password}}",
  "newPassword": "{{newPassword}}"
}

### Update password - wrong current password
PATCH {{baseUrl}}/users/me/password
Content-Type: application/json
Cookie: rs_app_session={{sessionCookie}}

{
  "currentPassword": "WrongPassword123!",
  "newPassword": "Password1234!"
}
