export const ADMIN_AUDIT_EVENT_TYPES = {
    catalogProposalsAccept: 'catalog.proposals.accept',
    catalogProposalsAlias: 'catalog.proposals.alias',
    catalogProposalsAssociate: 'catalog.proposals.associate',
    catalogProposalsList: 'catalog.proposals.list',
    catalogProposalsReject: 'catalog.proposals.reject',
    commentsDelete: 'comments.delete',
    commentsHide: 'comments.hide',
    commentsRestore: 'comments.restore',
    commentsUnmoderate: 'comments.unmoderate',
    commentsUpdate: 'comments.update',
    ingredientAliasesCreate: 'ingredients.aliases.create',
    ingredientAliasesDelete: 'ingredients.aliases.delete',
    ingredientAliasesList: 'ingredients.aliases.list',
    ingredientAliasesUpdate: 'ingredients.aliases.update',
    ingredientsCreate: 'ingredients.create',
    ingredientsDeprecate: 'ingredients.deprecate',
    ingredientsList: 'ingredients.list',
    ingredientsMerge: 'ingredients.merge',
    ingredientsRestore: 'ingredients.restore',
    ingredientsUpdate: 'ingredients.update',
    recipesApprove: 'recipes.approve',
    recipesArchive: 'recipes.archive',
    recipesDelete: 'recipes.delete',
    recipesReject: 'recipes.reject',
    staffDisable: 'staff.disable',
    staffEnable: 'staff.enable',
    staffInvitationCreate: 'staff.invitations.create',
    staffList: 'staff.list',
    staffRead: 'staff.read',
    staffRoleGrant: 'staff.roles.grant',
    staffRoleRevoke: 'staff.roles.revoke',
    staffSessionList: 'staff.sessions.list',
    staffSessionRevoke: 'staff.sessions.revoke',
    tagsCreate: 'tags.create',
    tagsDeprecate: 'tags.deprecate',
    tagsList: 'tags.list',
    tagsMerge: 'tags.merge',
    tagsRestore: 'tags.restore',
    tagsUpdate: 'tags.update',
    usersBan: 'users.ban',
    usersUnban: 'users.unban'
} as const;

export type AdminAuditEventType = (typeof ADMIN_AUDIT_EVENT_TYPES)[keyof typeof ADMIN_AUDIT_EVENT_TYPES];

export const ADMIN_AUDIT_TARGET_TYPES = {
    catalogProposal: 'catalog_proposal',
    catalogProposalCollection: 'catalog_proposal_collection',
    comment: 'comment',
    communityUser: 'community_user',
    ingredient: 'ingredient',
    ingredientAlias: 'ingredient_alias',
    ingredientCollection: 'ingredient_collection',
    recipe: 'recipe',
    staffCollection: 'staff_collection',
    staffInvitation: 'staff_invitation',
    staffSession: 'staff_session',
    staffUser: 'staff_user',
    tag: 'tag',
    tagCollection: 'tag_collection'
} as const;

export type AdminAuditTargetType = (typeof ADMIN_AUDIT_TARGET_TYPES)[keyof typeof ADMIN_AUDIT_TARGET_TYPES];

export const ADMIN_AUDIT_EVENT_TARGET_TYPES: Readonly<Record<AdminAuditEventType, AdminAuditTargetType>> = {
    [ADMIN_AUDIT_EVENT_TYPES.catalogProposalsAccept]: ADMIN_AUDIT_TARGET_TYPES.catalogProposal,
    [ADMIN_AUDIT_EVENT_TYPES.catalogProposalsAlias]: ADMIN_AUDIT_TARGET_TYPES.catalogProposal,
    [ADMIN_AUDIT_EVENT_TYPES.catalogProposalsAssociate]: ADMIN_AUDIT_TARGET_TYPES.catalogProposal,
    [ADMIN_AUDIT_EVENT_TYPES.catalogProposalsList]: ADMIN_AUDIT_TARGET_TYPES.catalogProposalCollection,
    [ADMIN_AUDIT_EVENT_TYPES.catalogProposalsReject]: ADMIN_AUDIT_TARGET_TYPES.catalogProposal,
    [ADMIN_AUDIT_EVENT_TYPES.commentsDelete]: ADMIN_AUDIT_TARGET_TYPES.comment,
    [ADMIN_AUDIT_EVENT_TYPES.commentsHide]: ADMIN_AUDIT_TARGET_TYPES.comment,
    [ADMIN_AUDIT_EVENT_TYPES.commentsRestore]: ADMIN_AUDIT_TARGET_TYPES.comment,
    [ADMIN_AUDIT_EVENT_TYPES.commentsUnmoderate]: ADMIN_AUDIT_TARGET_TYPES.comment,
    [ADMIN_AUDIT_EVENT_TYPES.commentsUpdate]: ADMIN_AUDIT_TARGET_TYPES.comment,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientAliasesCreate]: ADMIN_AUDIT_TARGET_TYPES.ingredientAlias,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientAliasesDelete]: ADMIN_AUDIT_TARGET_TYPES.ingredientAlias,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientAliasesList]: ADMIN_AUDIT_TARGET_TYPES.ingredient,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientAliasesUpdate]: ADMIN_AUDIT_TARGET_TYPES.ingredientAlias,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientsCreate]: ADMIN_AUDIT_TARGET_TYPES.ingredient,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientsDeprecate]: ADMIN_AUDIT_TARGET_TYPES.ingredient,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientsList]: ADMIN_AUDIT_TARGET_TYPES.ingredientCollection,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientsMerge]: ADMIN_AUDIT_TARGET_TYPES.ingredient,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientsRestore]: ADMIN_AUDIT_TARGET_TYPES.ingredient,
    [ADMIN_AUDIT_EVENT_TYPES.ingredientsUpdate]: ADMIN_AUDIT_TARGET_TYPES.ingredient,
    [ADMIN_AUDIT_EVENT_TYPES.recipesApprove]: ADMIN_AUDIT_TARGET_TYPES.recipe,
    [ADMIN_AUDIT_EVENT_TYPES.recipesArchive]: ADMIN_AUDIT_TARGET_TYPES.recipe,
    [ADMIN_AUDIT_EVENT_TYPES.recipesDelete]: ADMIN_AUDIT_TARGET_TYPES.recipe,
    [ADMIN_AUDIT_EVENT_TYPES.recipesReject]: ADMIN_AUDIT_TARGET_TYPES.recipe,
    [ADMIN_AUDIT_EVENT_TYPES.staffDisable]: ADMIN_AUDIT_TARGET_TYPES.staffUser,
    [ADMIN_AUDIT_EVENT_TYPES.staffEnable]: ADMIN_AUDIT_TARGET_TYPES.staffUser,
    [ADMIN_AUDIT_EVENT_TYPES.staffInvitationCreate]: ADMIN_AUDIT_TARGET_TYPES.staffInvitation,
    [ADMIN_AUDIT_EVENT_TYPES.staffList]: ADMIN_AUDIT_TARGET_TYPES.staffCollection,
    [ADMIN_AUDIT_EVENT_TYPES.staffRead]: ADMIN_AUDIT_TARGET_TYPES.staffUser,
    [ADMIN_AUDIT_EVENT_TYPES.staffRoleGrant]: ADMIN_AUDIT_TARGET_TYPES.staffUser,
    [ADMIN_AUDIT_EVENT_TYPES.staffRoleRevoke]: ADMIN_AUDIT_TARGET_TYPES.staffUser,
    [ADMIN_AUDIT_EVENT_TYPES.staffSessionList]: ADMIN_AUDIT_TARGET_TYPES.staffUser,
    [ADMIN_AUDIT_EVENT_TYPES.staffSessionRevoke]: ADMIN_AUDIT_TARGET_TYPES.staffSession,
    [ADMIN_AUDIT_EVENT_TYPES.tagsCreate]: ADMIN_AUDIT_TARGET_TYPES.tag,
    [ADMIN_AUDIT_EVENT_TYPES.tagsDeprecate]: ADMIN_AUDIT_TARGET_TYPES.tag,
    [ADMIN_AUDIT_EVENT_TYPES.tagsList]: ADMIN_AUDIT_TARGET_TYPES.tagCollection,
    [ADMIN_AUDIT_EVENT_TYPES.tagsMerge]: ADMIN_AUDIT_TARGET_TYPES.tag,
    [ADMIN_AUDIT_EVENT_TYPES.tagsRestore]: ADMIN_AUDIT_TARGET_TYPES.tag,
    [ADMIN_AUDIT_EVENT_TYPES.tagsUpdate]: ADMIN_AUDIT_TARGET_TYPES.tag,
    [ADMIN_AUDIT_EVENT_TYPES.usersBan]: ADMIN_AUDIT_TARGET_TYPES.communityUser,
    [ADMIN_AUDIT_EVENT_TYPES.usersUnban]: ADMIN_AUDIT_TARGET_TYPES.communityUser
};
